### ISSUE TITLE
[Question] Decision for static-site generator technology

### ISSUE THREAD

**Issue by sbliven** [SwissOpenEM/swissopenem.github.io#1]
@dwiessner-unibe suggests using docusaurus for the website.

> Docusaurus is a static-site generator. It builds a single-page application with fast client-side navigation, leveraging the full power of React to make your site interactive. It provides out-of-the-box documentation features but can be used to create any kind of site (personal website, product, blog, marketing landing pages, etc).

The main difference to jekyll seems to be that it uses React for the front-end. Authoring uses [MDX](https://mdxjs.com/) (markdown with extensions for inline js components).

Should we convert the site from jekyll to docusaurus?

**Comment by sbliven** [comment]
I'm generally not a big fan of single page apps unless you want to use a lot of interactive components. If we're just using react for the navigation bar then I don't see an advantage over jekyll. Some of the templates look nice; if we prefer some particular template that could be enough reason to switch site generator.

**Comment by sbliven** [comment]
I suggest that we postpone this for now until we have a clear plan for the website look and content. At that point we can better evaluate whether we need some React features beyond the current Hydejack theme.

**Comment by dwiessner-unibe** [comment]
I renamed the task, because there are different ideas for technologies.

- Jekyll (is used right now, based on Ruby) - https://jekyllrb.com/
- MkDocs (Philipp used it for ETH documentation) - https://www.mkdocs.org/
- Docusaurus (David has expierence with react and docusaurus) - https://docusaurus.io/

All use MD-pages for their content. There is no special functionality planned for the education page - if we decide on a nice template we can also decide for the technology. For now its more important to define the content.
